export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    LAWYERS: '/lawyers',
    LAWYER_DETAIL: '/lawyers/:id',
    PRACTICE_AREAS: '/practice-areas',
    HOW_IT_WORKS: '/how-it-works',
    ABOUT: '/about',
    FAQ: '/faq',
    CONTACT: '/contact',
    LOGIN: '/login',
    REGISTER: '/register',
    PRIVACY: '/privacy',
    TERMS: '/terms',
    DISCLAIMER: '/disclaimer',
  },
  CLIENT: {
    ROOT: '/client',
    DASHBOARD: '/client/dashboard',
    LAWYERS: '/client/lawyers',
    CONSULTATIONS: '/client/consultations',
    MATTERS: '/client/matters',
    MATTER_DETAIL: '/client/matters/:id',
    MESSAGES: '/client/messages',
    DOCUMENTS: '/client/documents',
    CALENDAR: '/client/calendar',
    HEARINGS: '/client/hearings',
    PAYMENTS: '/client/payments',
    NOTIFICATIONS: '/client/notifications',
    PROFILE: '/client/profile',
    LEGAL_DOCUMENTS: '/client/legal-documents',
  },
  LAWYER: {
    DASHBOARD: '/lawyer/dashboard',
    REQUESTS: '/lawyer/requests',
    CLIENTS: '/lawyer/clients',
    MATTERS: '/lawyer/matters',
    MATTER_DETAIL: '/lawyer/matters/:id',
    CALENDAR: '/lawyer/calendar',
    HEARINGS: '/lawyer/hearings',
    MESSAGES: '/lawyer/messages',
    DOCUMENTS: '/lawyer/documents',
    EARNINGS: '/lawyer/earnings',
    PROFILE: '/lawyer/profile',
    VERIFICATION: '/lawyer/verification',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    LAWYERS: '/admin/lawyers',
    VERIFICATION: '/admin/verification',
    BOOKINGS: '/admin/bookings',
    MATTERS: '/admin/matters',
    PAYMENTS: '/admin/payments',
    REPORTS: '/admin/reports',
    SETTINGS: '/admin/settings',
  },
} as const;
