import React from 'react';
import { useSEO } from '@/hooks/useSEO';
import { AlertOctagon, ShieldAlert } from 'lucide-react';

export const DisclaimerPage: React.FC = () => {
  useSEO({
    title: 'Legal Disclaimer & Regulatory Scope — ApkaLawyer',
    description: 'Explicit legal disclaimer regarding platform scope, automated templates, and advocate representation.',
  });

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-neutral-100 text-neutral-900 text-xs font-semibold mb-4 border border-neutral-200">
        <AlertOctagon className="h-3.5 w-3.5 text-neutral-900" />
        <span>Mandatory Statutory & Platform Disclaimer</span>
      </div>

      <h1 className="text-3xl font-semibold text-neutral-950 tracking-tight mb-3">Legal Disclaimer</h1>
      <p className="text-xs text-neutral-500 mb-8">Applicable across all public, client, and lawyer touchpoints.</p>

      <div className="space-y-6 text-sm text-neutral-700 leading-relaxed">
        <div className="p-6 rounded-lg bg-neutral-50 border border-neutral-200 text-neutral-900">
          <h3 className="font-semibold text-sm mb-2 flex items-center gap-2 text-neutral-950">
            <ShieldAlert className="h-4 w-4 text-neutral-800" />
            No Direct Legal Representation by ApkaLawyer
          </h3>
          <p className="text-xs text-neutral-600 leading-relaxed">
            The information provided on this website and software application does not, and is not intended to, constitute direct legal advice from ApkaLawyer. All content, materials, and information available on this platform are for general informational purposes only.
          </p>
        </div>

        <section className="p-6 rounded-lg bg-white border border-neutral-200 space-y-4">
          <h2 className="text-sm font-semibold uppercase tracking-wider text-neutral-900">Clear Separation of Product Elements</h2>
          
          <div className="space-y-4 text-xs">
            <div className="flex items-start gap-3">
              <span className="h-1.5 w-1.5 rounded-full bg-neutral-900 mt-1.5 flex-shrink-0" />
              <div>
                <strong className="text-neutral-950">1. Platform Information:</strong> General explanations of court hierarchies, legal practice areas, and procedural steps do not replace customized counsel from a licensed advocate.
              </div>
            </div>

            <div className="flex items-start gap-3">
              <span className="h-1.5 w-1.5 rounded-full bg-neutral-900 mt-1.5 flex-shrink-0" />
              <div>
                <strong className="text-neutral-950">2. Lawyer-Provided Legal Advice:</strong> Legal counsel and formal representations are provided solely by independent Advocates of the High Courts / Supreme Court who are retained by you through formal engagement.
              </div>
            </div>

            <div className="flex items-start gap-3">
              <span className="h-1.5 w-1.5 rounded-full bg-neutral-900 mt-1.5 flex-shrink-0" />
              <div>
                <strong className="text-neutral-950">3. Automated & AI Drafts:</strong> Legal notice generators, tenancy agreement wizards, and NDAs generated by the platform are <em>preliminary drafts only</em>. They do not constitute official legal advice and should be reviewed by an advocate before signing or serving.
              </div>
            </div>

            <div className="flex items-start gap-3">
              <span className="h-1.5 w-1.5 rounded-full bg-neutral-900 mt-1.5 flex-shrink-0" />
              <div>
                <strong className="text-neutral-950">4. Lawyer-Reviewed Filings:</strong> Only documents reviewed, signed, and stamped by an enrolled Advocate with a valid Vakalatnama can be filed before Pakistani courts.
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
};
